---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos65
    driver_config:
      box: /Users/cdongsi/Downloads/centos65.box

suites:
  - name: default
    run_list:
      - recipe[apache::default]
    attributes:
